FactoryBot.define do
  factory :sop_callback, class: "Sop::Callback" do
    association :instance, factory: :sop_instance
    sequence(:step_id) { |n| "step-#{n}" }
    status { "pending" }
    response { {} }
    expires_at { 7.days.from_now }
    # callback_path auto-generated by Sop::Callback#generate_callback_path

    trait :received do
      status { "received" }
      response { { "ok" => true } }
    end

    trait :expired do
      status { "expired" }
    end
  end
end
